stages:
  - build-and-test

image: debian:latest

build-and-test: 
  stage: build-and-test
  variables:
    SCALENODE_CPU: 16
    SCALENODE_RAM: 16000
  script:
    - apt-get update &> /dev/null
    - apt-get -y --no-install-recommends install
      autoconf bc bison build-essential ca-certificates ccache clang curl device-tree-compiler flex fuse3 libfl-dev
      gawk git gnupg help2man libelf-dev libusb-1.0-0-dev lsb-release mold python-is-python3 python3 python3-full python3-pip
      python3-pyelftools python3-setuptools python3-venv python3-venv srecord sudo tzdata unzip xxd zip 1> /dev/null
      # Packages taken from coralnpu/utils/coralnpu.dockerfile as well as verilator ci files
    - curl -fsSL https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor --yes -o /usr/share/keyrings/adoptium.gpg
    - printf "%s\n" "Types:deb" "URIs:https://packages.adoptium.net/artifactory/deb" "Suites:$(. /etc/os-release &&
      echo "$VERSION_CODENAME")" 'Components:main' "Architectures:$(dpkg --print-architecture)" "Signed-By:/usr/share/keyrings/adoptium.gpg" |
      sudo tee /etc/apt/sources.list.d/adoptium.sources > /dev/null
    - curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > /tmp/bazel-archive-keyring.gpg
    - mv /tmp/bazel-archive-keyring.gpg /usr/share/keyrings/
    - echo "deb [arch=$(dpkg-architecture -q DEB_HOST_ARCH) signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg]
      https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
    - apt update &> /dev/null
    - apt install -y --no-install-recommends bazel bazel-7.4.1 temurin-17-jdk temurin-17-jre
    - useradd -m builder
    - chown -R builder:root .
    - pushd ..
    - git clone https://github.com/verilator/verilator
    - pushd verilator && chown -R builder:root . &&  autoconf && ./configure && sudo -u builder make -j $(nproc)
      && export VERILATOR_ROOT=`pwd` && popd
    - git clone https://github.com/google-coral/coralnpu-mpact.git
    - pushd coralnpu-mpact && git checkout 61a6317aca4de62a4862181d24dc22a1795bda43 && chown -R builder:root . 
      && sudo -u builder  bazel build //sim/cosim:coralnpu_cosim_lib_static && export CORALNPU_MPACT=`pwd` && popd
    - popd
    - git clone https://github.com/chipsalliance/uvm-verilator.git -b uvm-1.2
    - cd uvm-verilator && git cherry-pick -n --strategy=recursive -X theirs 5a37baacfed0722b523b05decc9b94fe3e9efbe4 && export UVM=`pwd` && cd ..
    - sudo -u builder bazel build //hdl/chisel/src/coralnpu:rvv_core_mini_verification_axi_cc_library_emit_verilog
    - sudo -u builder VERILATOR_ROOT=$VERILATOR_ROOT PATH=$VERILATOR_ROOT/bin:$PATH CORALNPU_MPACT=$CORALNPU_MPACT UVM=$UVM
      python3 utils/run_uvm_regression.py --simulator=verilator
